### ISSUE TITLE
Invalid tag name for react dependency

### ISSUE THREAD

**Issue by pascaldevink** [uyarn/react-use-firework#1]
While installing this library, I'm getting the following error:
```
npm ERR! code EINVALIDTAGNAME
npm ERR! Invalid tag name ">=^16.9.0": Tags may not have any characters that encodeURIComponent encodes.
```

I believe this is due to the `react` peer dependency.

**Comment by uyarn** [comment]
hi, @pascaldevink, big thanks for this issue!😊
It seems to happen in npm 7.x and I have resolved it.
Please try the new release v1.0.2
